src/web/urls.py
from django.urls import path

from web.views import home, identifier, trouver, algue, cuisiner, recette, galerie, plage, get_plages, menu, apropos

urlpatterns = [
	path('', menu),
	path('menu/', menu),
	path('identifier/', identifier),
	path('trouver/', trouver),
	path('algue/<slug:slug>/', algue),
	path('cuisiner/', cuisiner),
	path('recette/<slug:slug>/', recette),
	path('galerie/', galerie),
	path('plage/', plage),
	path('get-plages/', get_plages),
	path('apropos/', apropos),
]

src/web/models.py
from django.db import models

from slugify import slugify

class Photo(models.Model):

    nom = models.CharField(max_length=200)
    modified_date = models.DateTimeField(auto_now=True)
    image = models.ImageField(upload_to="image/")
    description = models.TextField(max_length=2000, null=True, blank=True)

    def __str__(self):
        return self.nom

class Algue(models.Model):
    ALGUE_TYPES = (
        ('V', 'verte'),
        ('B', 'brune'),
        ('R', 'rouge'),
    )
    SUBSTRAT_TYPES = (
        ('R', 'Rocheux'),
        ('S', 'Sableux'),
    )

    slug = models.SlugField(max_length=200, unique=True)
    nom = models.CharField(max_length=200, null=True, blank=False)
    nom_scientifique = models.CharField(max_length=200, null=True, blank=False)
    modified_date = models.DateTimeField(auto_now=True)
    couleur = models.CharField(max_length=16, choices=ALGUE_TYPES, null=True, blank=False)
    categories = models.TextField(max_length=200, null=True, blank=True)
    miniature = models.ForeignKey(Photo, on_delete=models.SET_NULL, null=True, blank=True, related_name="algue_miniature")
    photos = models.ManyToManyField(Photo)
    funfact = models.TextField(max_length=2000, null=True, blank=True)
    # identification
    substrat = models.CharField(max_length=16, choices=SUBSTRAT_TYPES, null=True, blank=True)
    taille_adulte = models.CharField(max_length=200, null=True, blank=True)
    emplacement_estran = models.ForeignKey(Photo, on_delete=models.SET_NULL, null=True, blank=True, related_name="algue_emplacement_estran")
    silhouette_forme = models.ForeignKey(Photo, on_delete=models.SET_NULL, null=True, blank=True, related_name="algue_silhouette_forme")
    description = models.TextField(max_length=2000, null=True, blank=True)
    habitat = models.TextField(max_length=2000, null=True, blank=True)
    # bonnes pratiques récoltes
    disponibilite = models.CharField(max_length=200, null=True, blank=True)
    periode_recolte_legale = models.CharField(max_length=200, null=True, blank=True)
    recolte_taille = models.CharField(max_length=200, null=True, blank=True)
    recolte_position_coupe = models.ForeignKey(Photo, on_delete=models.SET_NULL, null=True, blank=True, related_name="algue_recolte_position_coupe")
    recolte_description = models.TextField(max_length=2000, null=True, blank=True)
    # nutriments
    nutrition_categories = models.TextField(max_length=200, null=True, blank=True)
    nutrition_tableau = models.TextField(max_length=2000, null=True, blank=True)
    nutrition_description = models.TextField(max_length=2000, null=True, blank=True)
    # autres
    bibliographie = models.TextField(max_length=2000, null=True, blank=True)
    publier = models.BooleanField(default=True)

    def save(self, *args, **kwargs):
        self.slug = slugify(self.nom)
        return super().save(*args, **kwargs)

    def __str__(self):
        return  "{} ({})".format(self.nom, self.nom_scientifique)

class Plage(models.Model):

    nom = models.CharField(max_length=200)
    modified_date = models.DateTimeField(auto_now=True)
    adresse = models.CharField(max_length=400, null=True, blank=True)
    latitude = models.FloatField()
    longitude = models.FloatField()
    algues = models.ManyToManyField(Algue, blank=True)
    qualite = models.BooleanField(default=True)
    publier = models.BooleanField(default=True)
    auteur_name = models.CharField(max_length=200, null=True, blank=False, default="Consomalgues")
    auteur_mail = models.CharField(max_length=200, null=True, blank=True, default="consomalgues@gmail.com")
    auteur_web = models.CharField(max_length=200, null=True, blank=True, default="https://www.consomalgues.fr/")

    def __str__(self):
        return self.nom

class Recette(models.Model):

    RECETTE_TYPES = (
        ('A', 'Apéritif'),
        ('E', 'Entrée'),
        ('P', 'Plat'),
        ('D', 'Dessert'),
    )

    DIFFICULTE = (
        ('F', 'Facile'),
        ('M', 'Moyenne'),
        ('D', 'Difficile'),
    )

    nom = models.CharField(max_length=200)
    slug = models.SlugField(max_length=200, unique=True)
    modified_date = models.DateTimeField(auto_now=True)
    miniature = models.ForeignKey(Photo, on_delete=models.SET_NULL, null=True, blank=True, related_name="recette_miniature")
    photos = models.ManyToManyField(Photo)
    algues = models.ManyToManyField(Algue, blank=True)
    personnes = models.IntegerField()
    temps = models.CharField(max_length=200)
    type = models.CharField(max_length=200, choices=RECETTE_TYPES)
    difficulte = models.CharField(max_length=200, choices=DIFFICULTE)
    ingredients = models.TextField(max_length=2000, null=True, blank=True)
    ustensiles = models.TextField(max_length=2000, null=True, blank=True)
    etapes = models.TextField(max_length=2000, null=True, blank=True)
    auteur_name = models.CharField(max_length=200, null=True, blank=False, default="Consomalgues")
    auteur_mail = models.CharField(max_length=200, null=True, blank=True, default="consomalgues@gmail.com")
    auteur_web = models.CharField(max_length=200, null=True, blank=True, default="https://www.consomalgues.fr/")
    publier = models.BooleanField(default=True)

    def save(self, *args, **kwargs):
        self.slug = slugify(self.nom)
        return super().save(*args, **kwargs)

    def __str__(self):
        return self.nom

src/web/templates/algue.html
{% extends 'base.html' %}
{% load static %}
{% block title %}Consomalgues | Algue{% endblock %}
{% block body_class %}
content-color
{% endblock %}
{% block content %}
<div class="specie-title">
    <h1 class="name">{{ algue.nom }} <i>{{ algue.nom_scientifique }}</i></h1>
    <h2 class="seaweed-color-text-{{ algue.get_couleur_display }}" id="onglet">Signalétique</h2>
</div>
<div class="w3-container macdonalgue-height-nav-algue main-menu-background" style="overflow: auto;">
        <div style="overflow: auto;">

            <div id="tab-1" class="content-specie">
                <div class="w3-content w3-display-container" style="max-width:800px; width: 100%; height: 100%; display: block;">
                    {% for photo in photos %}
                        <img class="img-slide-seaweed noselect" src="/media/{{ photo.image }}" style="width:100%" />
                    {% endfor %}
                    <div class="w3-center w3-container w3-section w3-large w3-text-white w3-display-bottommiddle" style="width:100%">
                        {% for photo in photos %}
                            <span class="w3-badge dot-img-seaweed w3-border-macdonalgue w3-transparent noselect"></span>
                        {% endfor %}
                    </div>
                </div>
                <p class="tags">
                    {% if categorieTags %}
                        {% for cat in categorieTags %}
                        <span class="w3-tag w3-small seaweed-color-{{ algue.get_couleur_display }}">#{{ cat | title}}</span>
                        {% endfor %}
                    {% endif %}
                </p>
                {% if algue.funfact %}
                    <p class="funfact funfact-color-{{ algue.get_couleur_display }}">{{ algue.funfact }}</p>
                {% endif %}
            </div>

            <div id="tab-2" class="content-specie" style="display:none">
                <p class="tags">
                    <span class="w3-tag w3-small seaweed-color-{{ algue.get_couleur_display }}">#{{ algue.get_couleur_display | title}}</span>
                    <span class="w3-tag w3-small seaweed-color-{{ algue.get_couleur_display }}">#Subrstrat{{ algue.get_substrat_display | title}}</span>
                    <span class="w3-tag w3-small seaweed-color-{{ algue.get_couleur_display }}">#{{ algue.taille_adulte }} (adulte)</span>
                </p>
                <h3 class="seaweed-color-text-{{ algue.get_couleur_display }}">Description et Silhouette</h3>
                <div class="flex-row">
                    {% if algue.description %}
                    <div class="flex-three">
                        <p class="funfact funfact-color-{{ algue.get_couleur_display }}">{{ algue.description }}</p>
                    </div>
                {% endif %}
                    {% if algue.silhouette_forme %}
                        <div class="flex-center flex-two">
                            <img src="{{ algue.silhouette_forme.image.url }}" style="width: calc(100% - 12px);"/>
                        </div>
                    {% endif %}
                </div>

                {% if algue.habitat %}
                    <h3 class="seaweed-color-text-{{ algue.get_couleur_display }}">Habitat</h3>
                    <p class="funfact funfact-color-{{ algue.get_couleur_display }}">{{ algue.habitat }}</p>
                {% endif %}

                {% if algue.emplacement_estran %}
                    <h3 class="seaweed-color-text-{{ algue.get_couleur_display }}">Emplacement sur l'estran</h3>
                    <img src="{{ algue.emplacement_estran.image.url }}" width="100%"/>
                {% endif %}
            </div>

            <div id="tab-3" class="content-specie" style="display:none">
                <h3 class="seaweed-color-text-{{ algue.get_couleur_display }}">Période idéale de récolte</h3>
                <div id="cycle">
                    <script>
                        createCycle('{{ algue.disponibilite }}');
                    </script>
                    <div class="flex-row-cycle">
                        <div class="cycle-legende cycle-1 flex-row">Récolte conseillée</div>
                        <div class="cycle-legende cycle-2 flex-row">Récolte possible</div>
                        <div class="cycle-legende cycle-3 flex-row">Non disponible</div>
                    </div>
                </div>
                {% if algue.periode_recolte_legale %}
                    <p>Récolte autorisée du {{ algue.periode_recolte_legale }}</p>
                {% endif %}

                <h3 class="seaweed-color-text-{{ algue.get_couleur_display }}">Conseils de récolte</h3>
                {% if algue.recolte_description %}
                    <p class="funfact funfact-color-{{ algue.get_couleur_display }}">{{ algue.recolte_description }}</p>
                {% endif %}
                {% if algue.recolte_taille %}
                    <p>Taille autorisée : {{ algue.recolte_taille }}</p>
                {% endif %}

                {% if algue.recolte_position_coupe %}
                    <h3 class="seaweed-color-text-{{ algue.get_couleur_display }}">Position de coupe</h3>
                    <div class="flex-center flex-two">
                        <img src="{{ algue.recolte_position_coupe.image.url }}" style="width: 50%;"/>
                    </div>
                {% endif %}
                </div>

            <div id="tab-4" class="content-specie" style="display:none">
                <p class="tags">
                    {% if categorieNutritionTags %}
                        {% for cat in categorieNutritionTags %}
                        <span class="w3-tag w3-small seaweed-color-{{ algue.get_couleur_display }}">#{{ cat | title}}</span>
                        {% endfor %}
                    {% endif %}
                </p>
                {% if algue.nutrition_description %}
                    <p class="funfact funfact-color-{{ algue.get_couleur_display }}">{{ algue.nutrition_description }}</p>
                {% endif %}

                {% if nutriments %}
                    <h3 class="seaweed-color-text-{{ algue.get_couleur_display }}">Composition (algue sèche)</h3>
                    <table class="nutriment">
                        <tr class="nutriment-header">
                            <td class="cell">Nutriments</td>
                            <td class="cell">Quantité (100g)</td>
                            <td class="cell">% <br/>AJR</td>
                            <td class="cell">Qualité nutritionnelle</td>
                        </tr>
                        {% for nutriment in nutriments %}
                                <tr class="{% cycle 'nutriment-1' 'nutriment-2' %}">
                                {% for cell in nutriment %}
                                    <td class="cell">
                                        {% if '*' in cell %}
                                            {% for c in cell %}
                                                {% if '*' in c %}
                                                    <img class="star" src="{% static 'img/star.png' %}"/>
                                                {% endif %}
                                            {% endfor %}
                                        {% else %}
                                            {{ cell }}
                                        {% endif %}
                                    </td>
                                {% endfor %}
                                </tr>
                        {% endfor %}

                    </table>

                    <table class="nutriment">
                        <tr>
                            <td class="cell">
                                <img class="star" src="{% static 'img/star.png' %}"/> faible
                            </td><td class="cell">
                                <img class="star" src="{% static 'img/star.png' %}"/>
                                <img class="star" src="{% static 'img/star.png' %}"/> moyenne
                            </td><td class="cell">
                                <img class="star" src="{% static 'img/star.png' %}"/>
                                <img class="star" src="{% static 'img/star.png' %}"/>
                                <img class="star" src="{% static 'img/star.png' %}"/> élévée
                        </tr>
                    </table>

                    <table class="nutriment">
                        <tr>
                            <td class="cell">
                                <img class="star" src="{% static 'img/star.png' %}"/>
                                <img class="star" src="{% static 'img/star.png' %}"/>
                                <img class="star" src="{% static 'img/star.png' %}"/>
                                <img class="star" src="{% static 'img/star.png' %}"/> très élévée
                            </td>
                            <td class="cell">
                                <img class="star" src="{% static 'img/star.png' %}"/>
                                <img class="star" src="{% static 'img/star.png' %}"/>
                                <img class="star" src="{% static 'img/star.png' %}"/>
                                <img class="star" src="{% static 'img/star.png' %}"/>
                                <img class="star" src="{% static 'img/star.png' %}"/> phénoménal
                            </td>
                        </tr>
                    </table>

                    <table class="nutriment"><tr><td>
                        AJR : Apport Journalier Recommandé pour un adulte-type (8400kJ/2000kcal)
                    </td></tr></table>

                {% endif %}
            </div>

            <div id="tab-5" class="content-specie" style="display:none">
                <div>
                	{% if recettes %}
                        {% include "recettes_liste.html" %}
        			{% endif %}
                </div>
            </div>

        </div>
    </div>
    <div class=" w3-bar w3-text-white macdonalgue-seaweed">
        <button class="w3-bar-item w3-button main-transparent" onclick="openPage(event, '/menu');">
            <img src="{% static 'img/icon-homex256-primary-vert.png' %}">
        </button>
        <button id="tab-1-icon" class="w3-bar-item w3-button" onclick="changeTab('tab-1', 'Signalétique')">
            <img src="{% static 'img/icon-seaweedx256-primary-vert.png' %}">
        </button>
        <button id="tab-2-icon" class="w3-bar-item w3-button" onclick="changeTab('tab-2', 'Identification')">
            <img src="{% static 'img/icon-loupex256-primary-vert.png' %}">
        </button>
        <button id="tab-3-icon" class="w3-bar-item w3-button" onclick="changeTab('tab-3', 'Bonne pratique de récolte')">
            <img src="{% static 'img/icon-scissorsx256-primary-vert.png' %}">
        </button>
        <button id="tab-4-icon" class="w3-bar-item w3-button" onclick="changeTab('tab-4', 'Alimentation')">
            <img src="{% static 'img/icon-pillx256-primary-vert.png' %}">
        </button>
        <button id="tab-5-icon" class="w3-bar-item w3-button" onclick="changeTab('tab-5', 'Recettes')">
            <img src="{% static 'img/icon-cookx256-primary-vert.png' %}">
        </button>
    </div>

    <script>
        let touchstartX = 0;
        let touchendX = 0;
        var slideIndex = 1;
        const initPage = () => {
            // init image
            let imgs = document.getElementsByClassName('img-slide-seaweed')
            let useTouch = false;
            try {
                useTouch = 'ontouchstart' in document.documentElement;
            } catch(e) {

            }

            for (const img of imgs ) {
                if (useTouch) {
                    img.addEventListener('touchstart', function(event) {
                        touchstartX = event.changedTouches[0].screenX;
                        touchstartY = event.changedTouches[0].screenY;
                    }, false);

                    img.addEventListener('touchend', function(event) {
                        touchendX = event.changedTouches[0].screenX;
                        touchendY = event.changedTouches[0].screenY;
                        handleGesture();
                    }, false);
                } else {
                    img.addEventListener('click', nextImg.bind(this, 1));
                }
            }
            showImg(slideIndex);

            // init content
            changeTab('tab-1', 'Signalétique');
        }
        document.addEventListener("DOMContentLoaded", initPage);
    </script>
</div>
{% endblock %}

src/web/templates/algues_liste.html
{% for algue in algues %}
    <div class="espece">
        <a href="/algue/{{ algue.slug }}" class="w3-button w3-padding-0 w3-margin-0 flex-line-list {{forloop.counter|divisibleby:2|yesno:"lightItem,darkItem"}}">

            <div class="seaweed-color-{{ algue.get_couleur_display }}-liseret">
                <img class="thumbail" src="/media/{{ algue.miniature.image }}"/>
            </div>

            <div class="listContentAlgue">
                <div class="listContent">
                    <span><b>{{ algue.nom }}</b></span>
                    <span class="small-text"><i>{{ algue.nom_scientifique }}</i></span>
                </div>

                {% if algue.harvest %}
                    <div class="harvest">
                        <span class="w3-tag w3-small seaweed-color-{{ algue.get_couleur_display }}">#RécolteNow!</span>
                    </div>
                {% endif %}
            </div>
        </a>
    </div>
{% endfor %}

src/web/templates/apropos.html
{% extends 'base.html' %}
{% load static %}
{% block title %}Consomalgues | A propos{% endblock %}
{% block body_class %}
content-color
{% endblock %}
{% block content %}
    <div class="w3-container macdonalgue-height-nav" style="overflow: auto;">
        <h3>Génèse du projet</h3>
        <p class="text-intro">
            Ce projet, porté par Solène Niqueux et plusieurs étudiants de l'UBS a débuté lors du Hackathon de la mer 2020, à Brest, sous le nom de macdonalgue.</a>
        </p>
        <p class="text-intro">
            Pour toute question, proposition de partenariat ou aide ponctuelle (contenu, recensement, test/bug), contactez l'équipe <a target="_blank" href="mailto:macdonalgue@gmail.com">consomalgues@gmail.com</a>.
        </p>

        <h3>Equipe</h3>
        <ul class="apropos">
            <li>Solène - Responsable projet</li>
            <li>Yannis - Responsable plages (spécialiste algues)</li>
            <li>Eléa - Responsable recettes (spécialiste algues)</li>
            <li>Armaëlle - Responsable algues (spécialiste algues)</li>
            <li>Laura (généraliste littoral)</li>
            <li>Valentin (généraliste littoral)</li>
            <li>Alan (spécialiste algues)</li>
            <li>Loïc - Responsable technique</li>
            <li>Dorian (développement logiciel)</li>
        </ul>

        <h3>Version de l'application</h3>
        <p class="text-intro">
            L'ensemble des données intégrées dans cette version (1.0) ont été vérifiée le 24/03/2021
        </p>

        <h3>Sources</h3>
        <p class="text-intro">
            Les données de l'application sont mises à jour régulièrement. Toutes les données de l'application sont issues de sources publiques libres dans un contexte d'utilisation gratuit. Voici la liste des sources utilisées :</a>
        </p>
        <ul>
            <li><a target="_blank" href="https://www.ceva-algues.com/document/">Site du CEVA</a></li>
            <li><a target="_blank" href="http://www.bretagne-peches.org/?titre=programme-biomasse-algues&mode=peche-a-pied&id=366">Rapport programme biomasse 2016-2019 du comité des pêches</a></li>
            <li><a target="_blank" href="https://www.finistere.gouv.fr/content/download/31817/240435/file/R53-2019-04-29-001_r%C3%A9colte_algues_Bretagne.pdf">Arrêté R53-2019-04-29-001 relatif à la récolte des algues en Bretagne</a></li>
            <li><a target="_blank" href="http://www.pecheapied-responsable.fr/">Site pêche à pied responsable (informations sanitaires)</a></li>
            <li><a target="_blank" href="https://meteofrance.com/">METEO France</a></li>
            <li><a target="_blank" href="http://maree.info">Maree Info</a></li>
        </ul>

        <h3>Avertissement</h3>
        <p class="text-intro">
            Cette application est optimisée pour les téléphones et les smartphones. Elle fonctionnera sur tablette et ordinateur mais ce sera moins joli !
        </p>
        <p class="text-intro">
            Les informations fournies, bien que sourcées et vérifiées, sont à titre informatif. L'application est réalisée par une équipe strictement bénévole, aucun acteur ne pourra être tenu comme responsable en cas de problème ou d'accident. Soyez attentifs, vérifiez vos sources et restez prudent !</a>
        </p>


    </div>
{% endblock %}

src/web/templates/base.html
<!DOCTYPE html>
{% load static %}
<html>
<head>
  <!-- Global site tag (gtag.js) - Google Analytics -->
  <script async src="https://www.googletagmanager.com/gtag/js?id=G-YFGC95N2TT"></script>
  <script> window.dataLayer = window.dataLayer || []; function gtag(){dataLayer.push(arguments);} gtag('js', new Date()); gtag('config', 'G-YFGC95N2TT'); </script>

  <meta charset="utf-8">
  <meta name='viewport' content='width=device-width, initial-scale=1, user-scalable=no'>
  <meta name="title" property="og:title" content="Consomalgues">
  <meta name="image" property="og:image" content="{% static 'networks/consomalgues.fr-recolte.jpg' %}">
  <meta name="description" property="og:description" content="Consomalgues, le site qui vous permet d'apprendre à identifier, trouver et consommer les algues du littoral breton !">
  <meta name="author" content="Brest Ocean Hackathon 2020 : Macdonalgue team">
  <meta name="url" content="https://consomalgues.fr">
  <meta name="keywords" content="algue, algues, seaweed, seaweeds, plage, plages, recette, recettes, sain, santé, avenir, futur, nourriture, alimentation, ecologie, bien-etre, progres">
  <title>{% block title %}Consomalgues{% endblock %}</title>
  <style>
    @font-face {
      font-family: 'Roboto';
      src: url('{% static 'fonts/Roboto-Regular.ttf' %}');
    }
  </style>

  <link rel="apple-touch-icon" sizes="180x180" href="{% static 'favicon/apple-touch-icon.png' %}">
  <link rel="icon" type="image/png" sizes="32x32" href="{% static 'favicon/favicon-32x32.png' %}">
  <link rel="icon" type="image/png" sizes="16x16" href="{% static 'favicon/favicon-16x16.png' %}">
  <link rel="manifest" href="{% static 'favicon/site.webmanifest' %}">

  <link rel="stylesheet" type="text/css" href="{% static 'css/w3.css' %}">
  <link rel="stylesheet" type="text/css" href="{% static 'css/macdonalgue.css' %}">
  {% block style %}
  {% endblock %}
  {% block script %}
  {% endblock %}
  <script src="{% static 'js/macdonalgue.js' %}"></script>
</head>
<body class="{% block body_class %}flex-column-center{% endblock %}">
  {% block content %}
  {% endblock %}
  {% if request.path != '/' and request.path != '/menu/' and '/algue' not in request.path %}
  {% block menu %}
    <div class=" w3-bar w3-text-white w3-white macdonalgue-nav">
        <button class="w3-bar-item w3-button" onclick="openPage(event, '/menu');">
            <img src="{% static 'img/icon-homex256-primary-vert.png' %}">
        </button>
        <button class="w3-bar-item w3-button {% if 'identifier' in request.path %}main-color-normal{% endif %}" onclick="openPage(event, '/identifier');">
            <img src="{% static 'img/icon-seaweedx256-primary-vert.png' %}">
        </button>
        <button class="w3-bar-item w3-button {% if 'trouver' in request.path %}main-color-normal{% endif %}" onclick="openPage(event, '/trouver');">
            <img src="{% static 'img/icon-mapx256-primary-vert.png' %}">
        </button>
        <button class="w3-bar-item w3-button {% if 'cuisiner' in request.path %}main-color-normal{% endif %}" onclick="openPage(event, '/cuisiner');">
            <img src="{% static 'img/icon-cookx256-primary-vert.png' %}">
        </button>
      </div>
    {% endblock %}
    {% endif %}
</body>
</html>

src/web/templates/galerie.html
{% extends 'base.html' %}
{% load static %}
{% block title %}Consomalgues | Galerie{% endblock %}

{% block content %}
:)
{% endblock %}

src/web/templates/plage.html
{% extends 'base.html' %}
{% load static %}
{% block title %}Consomalgues | Plage{% endblock %}

{% block content %}
:)
{% endblock %}

src/web/templates/recette.html
{% extends 'base.html' %}
{% load static %}
{% block title %}Consomalgues | Recette{% endblock %}
{% block body_class %}
content-color
{% endblock %}
{% block content %}
<div class="w3-container macdonalgue-height-nav" style="overflow: auto;">
        <div style="overflow: auto;" class="main-menu-background">
            <div class="specie-title">
                <h1 class="name">{{ recette.nom }}</h1>
                <span class="span-recepie">
                    {{ recette.get_difficulte_display }} -
                    {{ recette.temps }} -
                    {{ recette.personnes }}
                    {% if recette.personnes == 1 %}
                        personne
                    {% else %}
                        personnes
                    {% endif %} -
                    {{ recette.get_type_display }}
                </span>
            </div>
            <!--
            <div id='images' class="w3-container w3-white w3-height-images">
            </div>
            -->

            <div class="w3-content w3-display-container" style="max-width:800px; width: 100%; height: 100%; display: block;">
                {% for photo in photos %}
                    <img class="img-slide-seaweed noselect" src="/media/{{ photo.image }}" style="width:100%" />
                {% endfor %}
                <div class="w3-center w3-container w3-section w3-large w3-text-white w3-display-bottommiddle" style="width:100%">
                    {% for photo in photos %}
                        <span class="w3-badge dot-img-seaweed w3-border-macdonalgue w3-transparent noselect"></span>
                    {% endfor %}
                </div>
            </div>

            <div class="flex-center">
                {% include "share.html" %}
            </div>

            <div>
                <h3>Ingrédients</h3>
                <ul>
                	{% for ingredient in ingredients %}
                    <li class="ingredient">
                        <img class="ingredientImg noselect" src="{% static 'img/puce-carre-color-vert.png' %}" /> {{ ingredient }}
                    </li>
                    {% endfor %}
                </ul>
            </div>

            <div>
                <h3>Préparation</h3>
                <ul>
                	{% for etape in etapes %}
                    <li class="todo">
                        <img id="todo-{{forloop.counter}}" class="noselect" src="{% static 'img/checkbox-nocheck-color-vert.png' %}" onclick="checkUncheckStep('todo-{{forloop.counter}}');"/>
                        <label for="todo{{forloop.counter}}" onclick="checkUncheckStep('todo-{{forloop.counter}}');">{{ etape }}</label>
                    </li>
                    {% endfor %}
                </ul>
            </div>

            {% if recette.auteur_name %}
            <div class="auteur">
                <h3>Par {{ recette.auteur_name }}</h3>
                <ul>
                    {% if recette.auteur_web %}<li><a href="{{ recette.auteur_web }}" target="_blank">{{ recette.auteur_web }}</a></li>{% endif %}
                </ul>
            </div>
            {% endif %}

        </div>
</div>
<script>
    /* old mecanism
    // let currentImage = 0
	// let images = ['/media/{{ recette.photo.image }}']
	// loadImage();
    */

    let touchstartX = 0;
    let touchendX = 0;
    var slideIndex = 1;
    const initPage = () => {
        // init image
        let imgs = document.getElementsByClassName('img-slide-seaweed')
        let useTouch = false;
        try {
            useTouch = 'ontouchstart' in document.documentElement;
        } catch(e) {

        }

        for (const img of imgs ) {
            if (useTouch) {
                img.addEventListener('touchstart', function(event) {
                    touchstartX = event.changedTouches[0].screenX;
                    touchstartY = event.changedTouches[0].screenY;
                }, false);

                img.addEventListener('touchend', function(event) {
                    touchendX = event.changedTouches[0].screenX;
                    touchendY = event.changedTouches[0].screenY;
                    handleGesture();
                }, false);
            } else {
                img.addEventListener('click', nextImg.bind(this, 1));
            }
        }
        showImg(slideIndex);
    }
    document.addEventListener("DOMContentLoaded", initPage);
</script>


{% endblock %}

src/web/templates/recettes_liste.html
{% for recette in recettes %}
<div class="recepie">
    <a href="/recette/{{ recette.slug }}" class="w3-button w3-padding-0 w3-margin-0 flex-line-list {{forloop.counter|divisibleby:2|yesno:"lightItem,darkItem"}}">
        <div>
        <img class="thumbail" src="/media/{{ recette.miniature.image }}"/>
        </div>
        <div class="listContent">
            <span><b>{{ recette.nom }}</b></span>
            <span>
                {{ recette.get_difficulte_display }} -
                {{ recette.temps }} -
                {{ recette.personnes }}
                {% if recette.personnes == 1 %}
                    personne
                {% else %}
                    personnes
                {% endif %} -
                {{ recette.get_type_display }}
            </span>
        </div>
    </a>
</div>
{% endfor %}